"""empty message

Revision ID: a3215e9c331d
Revises: 
Create Date: 2021-09-20 13:46:21.658069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3215e9c331d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('exercise_name', sa.String(length=50), nullable=False),
    sa.Column('exercise_description', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('exercise_id')
    )
    op.create_table('routines',
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.Column('routine_name', sa.String(length=50), nullable=False),
    sa.Column('routine_description', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('routine_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('routine_exercises',
    sa.Column('routine_exercise_id', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.exercise_id'], ),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.routine_id'], ),
    sa.PrimaryKeyConstraint('routine_exercise_id')
    )
    op.create_table('user_routines',
    sa.Column('user_routine_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.routine_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_routine_id')
    )
    op.create_table('user__routine__exercises',
    sa.Column('personal_routine_exercise_id', sa.Integer(), nullable=False),
    sa.Column('user_routine_id', sa.Integer(), nullable=True),
    sa.Column('routine_exercise_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['routine_exercise_id'], ['routine_exercises.routine_exercise_id'], ),
    sa.ForeignKeyConstraint(['user_routine_id'], ['user_routines.user_routine_id'], ),
    sa.PrimaryKeyConstraint('personal_routine_exercise_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user__routine__exercises')
    op.drop_table('user_routines')
    op.drop_table('routine_exercises')
    op.drop_table('user')
    op.drop_table('routines')
    op.drop_table('exercises')
    # ### end Alembic commands ###
