"""empty message

Revision ID: a768190d9a6d
Revises: a8e2f53a563d
Create Date: 2021-09-08 15:36:43.014438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a768190d9a6d'
down_revision = 'a8e2f53a563d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routine_exercises', sa.Column('reps', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('password', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    op.drop_column('routine_exercises', 'reps')
    # ### end Alembic commands ###
