"""empty message

Revision ID: a8e2f53a563d
Revises: 8394f5929879
Create Date: 2021-08-30 16:26:56.414626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8e2f53a563d'
down_revision = '8394f5929879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('exercise_name', sa.String(length=50), nullable=False),
    sa.Column('exercise_description', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('exercise_id')
    )
    op.create_table('routine_exercises',
    sa.Column('routine_exercise_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.exercise_id'], ),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.routine_id'], ),
    sa.PrimaryKeyConstraint('routine_exercise_id')
    )
    op.create_table('user_routines',
    sa.Column('user_routine_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.routine_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_routine_id')
    )
    op.create_table('user__routine__exercises',
    sa.Column('personal_routine_exercise_id', sa.Integer(), nullable=False),
    sa.Column('user_routine_id', sa.Integer(), nullable=True),
    sa.Column('routine_exercise_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['routine_exercise_id'], ['routine_exercises.routine_exercise_id'], ),
    sa.ForeignKeyConstraint(['user_routine_id'], ['user_routines.user_routine_id'], ),
    sa.PrimaryKeyConstraint('personal_routine_exercise_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user__routine__exercises')
    op.drop_table('user_routines')
    op.drop_table('routine_exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
