"""empty message

Revision ID: d8e2ff647e45
Revises: a3215e9c331d
Create Date: 2021-09-28 13:55:09.741571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8e2ff647e45'
down_revision = 'a3215e9c331d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_routine_exercises',
    sa.Column('personal_routine_exercise_id', sa.Integer(), nullable=False),
    sa.Column('user_routine_id', sa.Integer(), nullable=True),
    sa.Column('routine_exercise_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['routine_exercise_id'], ['routine_exercises.routine_exercise_id'], ),
    sa.ForeignKeyConstraint(['user_routine_id'], ['user_routines.user_routine_id'], ),
    sa.PrimaryKeyConstraint('personal_routine_exercise_id')
    )
    op.create_table('logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('date_completed', sa.DateTime(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('personal_routine_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['personal_routine_id'], ['user_routine_exercises.routine_exercise_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.drop_table('user__routine__exercises')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user__routine__exercises',
    sa.Column('personal_routine_exercise_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_routine_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('routine_exercise_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['routine_exercise_id'], ['routine_exercises.routine_exercise_id'], name='user__routine__exercises_routine_exercise_id_fkey'),
    sa.ForeignKeyConstraint(['user_routine_id'], ['user_routines.user_routine_id'], name='user__routine__exercises_user_routine_id_fkey'),
    sa.PrimaryKeyConstraint('personal_routine_exercise_id', name='user__routine__exercises_pkey')
    )
    op.drop_table('logs')
    op.drop_table('user_routine_exercises')
    # ### end Alembic commands ###
